apiVersion: v1
kind: Service
metadata:
  name: notificacion-service
spec:
  selector:
    app: notificaciones
  ports:
    - protocol: TCP
      port: 8081 # PUERTO POR EL QUE EL SERVICIO VA A ESTAR ESCUCHANDO
      targetPort: 8081 # PUERTO AL QUE SE VA A DIRIGIR EL TRÁFICO QUE ENTRA POR "PORT"
