apiVersion: apps/v1
kind: Deployment
metadata:
  name: notificacion-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: notificaciones
  template:
    metadata:
      labels:
        app: notificaciones
    spec:
      containers:
        - name: notificacion
          image: pxrsival/notificaciones:1.0
          ports:
            - containerPort: 8081
