apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: notificaciones
  name: notificaciones
spec:
  replicas: 3
  selector:
    matchLabels:
      app: notificaciones
  template:
    metadata:
      labels:
        app: notificaciones
    spec:
      containers:
        - name: notificaciones
          image: pxrsival/notificaciones:1.0
          ports:
            - containerPort: 8081

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: notificaciones
  name: notificaciones
spec:
  selector:
    app: notificaciones
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80 # PUERTO POR EL QUE EL SERVICIO VA A ESTAR ESCUCHANDO
      targetPort: 8081 # PUERTO AL QUE SE VA A DIRIGIR EL TRÁFICO QUE ENTRA POR "PORT"
